### ISSUE TITLE
Is that possible to test it with MacOS and Docker?

### ISSUE THREAD

**Issue by SquirminatorHotHead** [MISTLab/DOOR-SLAM#1]
Hi there, thank you for sharing this project. I tested on my MacBook, then I realized X11Docker doesn't support macOS. I have a dumb question: is there anyone in your team using Docker + macOS to test it? If it's doable I think I will do some effort to make it work otherwise I am switching to Windows/Linux.

**Comment by lajoiepy** [comment]
Hi! None of us is working with macOS (only Linux), but it might be feasible. You could try this instead of X11Docker : https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285.

**Comment by beltrame** [comment]
Interestingly, I had replied to this message last week, but somehow the response didn't get through...

> Hello, thank you for your interest in DOOR-SLAM. To use X11 on Mac you should install XQuartz (or similar software), then in combination with Docker it would be just like being on X11/Linux. You can find several tutorials online on how to use XQuartz.

**Comment by SquirminatorHotHead** [comment]
@lajoiepy @beltrame Thank you!
