### ISSUE TITLE
h: No such file or directory  #include <loop_closure_transform/ReceiveLoopClosures.h>

### ISSUE THREAD

**Issue by flyover-26** [MISTLab/DOOR-SLAM#10]
Hello!

 when I installed BUZZ-SLAM,i got a problem like 
"In file included from /home/docker/robust_distributed_slam_simulation/Buzz_SLAM/src/generic_robot/buzz_generic_robot_slam_ros.cpp:3:0:
/home/docker/robust_distributed_slam_simulation/Buzz_SLAM/src/generic_robot/message_handler_utils/message_handler_utils.h:7:10: fatal error: loop_closure_transform/ReceiveLoopClosures.h: No such file or directory
 #include <loop_closure_transform/ReceiveLoopClosures.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/generic_robot_buzz_slam_node.dir/build.make:158: recipe for target 'CMakeFiles/generic_robot_buzz_slam_node.dir/generic_robot/buzz_generic_robot_slam_ros.cpp.o' failed
make[2]: *** [CMakeFiles/generic_robot_buzz_slam_node.dir/generic_robot/buzz_generic_robot_slam_ros.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/generic_robot_buzz_slam_node.dir/all' failed
make[1]: *** [CMakeFiles/generic_robot_buzz_slam_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2"
And i found the file buzz-slam has been updated by the author,so i changed it to the lastest one.But the name of this file changed from "buzz-slam" to "Buzz-SLAM". i tried to rewrite its name to "buzz-slam",but i got the same error .

Looking forward to your reply!!!

ps:
![proplem](https://user-images.githubusercontent.com/66856871/127590749-3fd39287-e6a5-4a73-9582-ff3fd839292d.png)

**Comment by lajoiepy** [comment]
Hi! 

Thanks for your interest in DOOR-SLAM!
Please make sure to use the git tag `DOOR-SLAM-1.0` when building the system. https://github.com/lajoiepy/Buzz_SLAM/tree/DOOR-SLAM-1.0
The new version is not compatible.

I will shortly fix the Dockerfiles accordingly!

**Comment by flyover-26** [comment]
Thanks for your reply!!!
if i use DOOR-SlAM-1.0,i got the problem below.
![wx_camera_1626525677190](https://user-images.githubusercontent.com/66856871/127681550-5844a659-5aa0-42b3-94c0-0bf3a515aee2.jpg)
And i found this library in another author's repository .But when i tried to catkin_make in the file of ros_ws from this author's repository,i got the new error below.
![wx_camera_1626857896314](https://user-images.githubusercontent.com/66856871/127681773-4e0102d7-d8d4-4838-b8bd-36bab7f85168.jpg)
i have no idea how to slove it.
Thanks so much for your reply!!!

**Comment by lajoiepy** [comment]
To build the whole system, please use this Dockerfile and instructions instead : https://github.com/bramtoula/multi_robot_SLAM_separators/tree/master/docker/camera_and_slam_tx2

**Comment by flyover-26** [comment]
Thank you so much for your patience!!!!
Should I use the Dockerfile you mentioned if I just want to get the result of simulation  only with my computer.Because I found the Dockerfile starts with "lajoiepy/realsense-tx2-px4".
Looking forward to your reply!!!

**Comment by lajoiepy** [comment]
For simulation only, please use this [Dockerfile and instructions](https://github.com/lajoiepy/robust_distributed_slam_simulation/tree/ea7f30212a0323a8f146954948818c6fbaaa611d/docker/devel)

**Comment by flyover-26** [comment]
Sorry to waste you so mush time.
I may not be able to express what I mean in vain.
All errors comes from the Dockerfile that is for simulation only .
When I tried to simulate,I got these errors.They are all from here.
![problem2](https://user-images.githubusercontent.com/66856871/127755999-16c3aa03-06a4-4e3a-a18b-c0050b8092de.png)

If i use DOOR-SLAM-1.0，I got an error mentioned before when I try to install Buzz SLAM .
![图片](https://user-images.githubusercontent.com/66856871/127756142-9ccb7089-c6ea-46ee-939c-6cf2d836bddb.png)

Thank you so much for your reply!!

**Comment by lajoiepy** [comment]
No problem :) Can you try the docker build with the `--no-cache` option? do you still have the same issue?

**Comment by flyover-26** [comment]
yes.I still get the same error.
![new](https://user-images.githubusercontent.com/66856871/127796681-9d54c55d-9d76-457c-a097-64d2018c93dd.png)

**Comment by flyover-26** [comment]
When I docker build it again.I got the same problem.
At the same time,it shows "No package argos_simulator found".I have no idea whether this has any effect on the result.
Looking forward to you reply!!!
![publish4](https://user-images.githubusercontent.com/66856871/127942379-f2f369f8-3f7a-44a8-95f9-66ed1a4cd90f.png)

**Comment by lajoiepy** [comment]
The simulator and third party libraries evolve continuously and DOOR-SLAM is no longer updated. For a stable experience to reproduce our results, I strongly suggest you to use the working docker image `lajoiepy/doorslam-argos-simulation` that we provide. If you are unfamiliar with Docker you can run `docker pull lajoiepy/doorslam-argos-simulation` to download it.

**Comment by flyover-26** [comment]
Thank you so much!!!The problem has been solved.

I want to test kitti on TX2 now.Could you please tell me how can I get the result?  I have  already  pulled images on TX2.
Looking forward to your replay!!!

**Comment by lajoiepy** [comment]
Hi!

First follow the setup here: https://github.com/MISTLab/DOOR-SLAM/blob/master/tx2-setup/docker/instructions.md
Then, split your KITTI ROS bag into 3 parts named `bag-0.bag`,  `bag-1.bag`, and `bag-2.bag`. Put one on each TX2 (you need 3 on the same network). Then launch the `kitti_params` commands from the aliases [here](https://github.com/MISTLab/DOOR-SLAM/blob/master/tx2-setup/docker/aliases.txt).

Have a nice day!

**Comment by flyover-26** [comment]
Thank you for your reply!!!!
I still have some problems.
If I have 2 TX2,is it necessary to split KITTI into 3 parts? And I have no idea where I should save these dataset exactly.(on TX2 itself or  in a container?) 
About setting paremeters,    are they related to network like MASK、OWN_IP .
When I try to launch kitti_params,the terminal says that the container is not running.And when I run images you provided ,I find the container exits immediately.And I run images like sudo docker run -it  lajoiepy/doorslam-realsensed435-tx2-dji.
Did I do something wong?
![1630140305733](https://user-images.githubusercontent.com/66856871/131212892-e3370eba-e4b6-4976-a7ae-e84bd15a5695.jpg)

Have a good day!!!

**Comment by lajoiepy** [comment]
You can do it on 2 TX2, look closely the bash commands in .bash_aliases to understand how it works (where to place files, etc.)
Before launch `kitti_params` you need a container running, to do this launch `docker_bash` first.

**Comment by flyover-26** [comment]
Thank you so much!
When I test kitti ,can I get other results except pose graph?like point cloud map?

**Comment by lajoiepy** [comment]
No, DOOR-SLAM doesn't currently support the production of a 3D map. However, you could save the 3D pointclouds from your sensors and use the pose graph to align them in post-processing.

**Comment by flyover-26** [comment]
I got it!!!
If I want to download KITTI dataset,I find the website according to A. Geiger, P. Lenz, and R. Urtasun, “Are we ready for autonomous driving? the KITTI vision benchmark suite,” in IEEE Conf. on Computer Vision and Pattern Recognition (CVPR), Providence, USA, June 2012, pp. 3354–3361.
But I have no idea which dataset I should download?Is this right place to download dataset you mentioned in your paper?(http://www.cvlibs.net/datasets/kitti/eval_stereo_flow.php?benchmark=stereo)
Thank you a lot!!!

**Comment by lajoiepy** [comment]
It is here: http://www.cvlibs.net/datasets/kitti/eval_odometry.php :)

**Comment by flyover-26** [comment]
I got it!
Thank you so much.
I try to download grayscale one.And I find it has left images and right images.now I can convert just one of them into .bag.I have no idea how to covert all of them into one .bag.
And if I split BAG into two parts,how much overlaps  shouldthey have?
thank you for your help!

**Comment by flyover-26** [comment]
Hi！
Sorry to take up your time.I am eager for the results.

I successfully put a Kitti Ros bag on one Tx2.But when I run Kitti-param ,I got some errors like "error while loading share libraries:libpcl.so.1.8:cannot open shared object file:No such file or directory"and "Import Error:libcublas.so.10.0:cannot open shared object file:No such file or directory"
![1631795714770](https://user-images.githubusercontent.com/66856871/133613072-7dde1b76-7118-40ec-9da2-5799747cda31.jpg)
![1631795756819](https://user-images.githubusercontent.com/66856871/133613160-46980849-9099-4f06-ae0b-2de3fafa4d37.jpg)
I flash the Tx2 with jetpack4.6.I guess this may not lead to these errors.
Looking for forward to your reply !

**Comment by lajoiepy** [comment]
We were using Jetpack 4.2 for the experiments, this might be the issue here.

**Comment by flyover-26** [comment]
THANK YOU SO MUCH！
The problem has been solved.
I download a dataset from internet and this is the information about this .bag.(this bag's topic is a little bit different from what we want.for example,/kitti/camera_color_left/image_raw.What we want is   /kitti/camera_color_left/image_rect.So I change the name of topic to what we want with the help of "rosbag record ")
![bag](https://user-images.githubusercontent.com/66856871/134349912-e34718af-cc72-4351-bf79-734498b05708.png)


And when I run kitti_param,I get an error below.
![IMG_20210922_203713](https://user-images.githubusercontent.com/66856871/134348501-6a53585f-90e4-4342-b15f-1ce44ec1df84.jpg)
It seems like DOOR-SLAM can not recieve data from this topic.But  when I use rostopic hz my_topic,these topics are sending messages.
![IMG_20210922_210727](https://user-images.githubusercontent.com/66856871/134350015-0f15d2e5-a61c-4abb-a1e8-7cd5173467cd.jpg)

I use this dataset to test ,because I don not kown how to transfer left images and right images into one rosbag.

Thank you for your reply!!!

**Comment by flyover-26** [comment]
The problem has been solved!
it seems that I get some results.
![1632539973125](https://user-images.githubusercontent.com/66856871/134756162-6c829614-785b-443c-b987-3f599dfb3f68.jpg)
could you tell me how I can get a pose graph pictures? I want to use rviz,but docker can not connect to X display.

**Comment by lajoiepy** [comment]
The resulting pose graph files should be in the `datasets` folder you created. They are in the g2o format (https://github.com/RainerKuemmerle/g2o). We do not provide a visualization tool, but you could use the one from g2o or others or make your own .

**Comment by flyover-26** [comment]
I got it!THANK YOU!!!

I want to add intel realsense to this experiment.But I use AGX Xavier.When I run ./buildPatchedKernel.sh,it does not provide L4Target 32.1.0.
Is this enough if I change

“if [ "$JETSON_BOARD" == "AGX Xavier" ] ; then 
  L4TTarget="31.1.0"
  # Test for 31.1.0 first
  if [ $JETSON_L4T = "31.1.0" ] ; then
     KERNEL_BUILD_VERSION=vL4T31.1.0”

to

if [ "$JETSON_BOARD" == "AGX Xavier" ] ; then 
  L4TTarget="32.1.0"
  # Test for 31.1.0 first
  if [ $JETSON_L4T = "32.1.0" ] ; then
     KERNEL_BUILD_VERSION=vL4T32.1.0

(ps:31.1.0 to 32.1.0)

Thank you for your reply!!!

**Comment by flyover-26** [comment]
hi! I find if I use jetpack4.2 to flash the agx xavier.I got the L4T 32.1 which is not included in your buildpached kernel.sh.But I found you take agx
 with L4T 31.1 into consider.
I Have to flash agx with jetpack 4.1.1 developer preview if I want to get L4T 32.1. but this is not the same with your suggestion about jetpack4.2.
![Uploading Screenshot_20211003_100531.jpg…]()

I have no idea what going on here?Looking forward to your reply!thank you so much!

**Comment by lajoiepy** [comment]
We were using the NVIDIA Jetson TX2 instead of the Xavier AGX, hence the difference in JetPack version. Unfortunately, I can not provide support on the Xavier AGX setup.

**Comment by flyover-26** [comment]
THANK YOU FOR YOUR REPLY！

I notice that in your readme.md you said it is for  librealsense v2.22.0.
But I see LIBREALSENSE_VERSION=v2.24.0 in your installLibrealsense.sh.

so the version of librealsense I got last is v2.24.0 .Am I right?

Is batman-adv module necessery?Because it is a little hard to install this on agx.
Thank you sooooo much!

**Comment by lajoiepy** [comment]
I don't think the exact version of the librealsense is important. You should take the latest working version for your computer and camera. `batman-adv` is not needed if you use a centralized network like wifi.

**Comment by flyover-26** [comment]
OK！THANK YOU！
I have two questions about this experiment.
Will I still get only pose graph result in datasets that I created If I use camera on TX2.If I want to visualize result,I also need to do it by myself.

The second question is that when I test kitti on TX2 last time, I find arithmetic speed is very slow.Is this normal?or right? How is the real-time nature of this project?
THANK YOU!!!

**Comment by lajoiepy** [comment]
The loop closures should be detected in real-time (or close to) if you have perfect communication. However if there are significant delays on your network, this makes the process slower. The pose graph optimization takes more time (usually less than a minute depending on the stopping threshold and the communication delays) and should be done periodically similar to other SLAM systems.

**Comment by flyover-26** [comment]
THANKS!!!
I tried to connect camera on agx,and I run the command "camera".But the docker told me that it can not find the divice.I notice that  the version of realsense ros is v2.27.0.But I find this version only support ubuntu 16.04.However  in your docker image,it is ubuntu 18.04.I have no idea whether this may cause the error.
Thank you so much for your help!!!
![librealsense](https://user-images.githubusercontent.com/66856871/137737559-c3536275-c53e-4569-beda-7357e3a0a286.jpg)
