### ISSUE TITLE
Question about launch command 'blabbermouth2'

### ISSUE THREAD

**Issue by hyungyu-Park** [MISTLab/DOOR-SLAM#12]
Hello?

I think DOOR SLAM can help me a lot with my research, so I'm studying.
But I'm having trouble running the code, so I'm leaving a message

I was planning to run this code to two TX2 boards and KITTI Dataset, and I finished setting it up by looking at the Quick Setup you wrote.
However, there was a problem running 'A typical sequence' after setting aliases and parameters.

I typed 'docker_bash' in two TX2 terminals, and the container was created. And the following error occurred while performing blabbermouth2 in Robot1.

![error](https://user-images.githubusercontent.com/48715608/193068771-350ae994-d229-4fac-9e32-65b94372a507.png)

I think there was a problem during the porting process of the container created in TX2. However, I tried many ways, but I couldn't solve the problem.

How can I solve this problem?

**Comment by lajoiepy** [comment]
Hi!
Can you double check that the IP addresses of the command (here: https://github.com/MISTLab/DOOR-SLAM/blob/6272059fd4f547df730466e1ae95abb503de1d89/tx2-setup/docker/aliases.txt#L20) correspond to the IP addresses of your TX2s?
It might also be a firewall issue preventing the connection.

**Comment by hyungyu-Park** [comment]
Thank you for your answer
Of course, 'alias blabbermouth2' also changed the IP address, but the problem I mentioned above occurred.

And you told me about the firewall, so I tried a few more things.
I turned off the TX2 firewall through `sudo ufw disable`, and tried the Wi-Fi and wired cable environments, but the same problem continued to occur.

Is there any other way I can try to remove the firewall?

**Comment by lajoiepy** [comment]
It seems it is not a firewalll issue then.
It might be a docker networking problem. Maybe the ports are not accessible from the host (or the opposite). You can take a look at: https://docs.docker.com/network/

**Comment by hyungyu-Park** [comment]
I've looked at the firewalls, ports, etc. once again and sorted out some of the questions (the same error is still occurring)

1. What do you mean by 10000($5) which is the input of blabbermouth in the 24th line of '`entrypoint.sh`'?
[            ./blabbermouth -s $5 1:tcp:1:192.168.$2.$6:24580 2:tcp:1:192.168.$2.$7:24581](https://github.com/MISTLab/DOOR-SLAM/blob/6272059fd4f547df730466e1ae95abb503de1d89/tx2-setup/docker/entrypoint.sh#L24)

2. The error **_'docker: network "host" is specified multiple times'_** occurred when entering `docker_bash` at the terminal. So I ran it without the '--net host' option and succeeded. Isn't this a problem? 
Of course, after that, I checked that the container created through '`docker network inspect host`' was connected to the host network.

3. Can't I forward the port between the local machine and the host network container? Wouldn't it be easy to access the container from outside if the port is mapped to the container even if the container is created through the host network?

4. Finally, do you have the Ubuntu desktop version of DOOR-SLAM code? If you do, can you reveal that, too?

**Comment by lajoiepy** [comment]
1. Maximum packet size.
2. I didn't get this error at the time, but it seems like an issue.
3. You can.
4. I don't unfortunately, but I am currently working on a new C-SLAM system that should be much better. It should be released in a couple of months.
Also it is important to mention that blabbermouth is not an essential part of the system, but just a tool that I have reused from another project. It might be easier to code your own solution adapted to your setup than trying to debug it. blabbermouth simply forwards packets published on each address:port to all the others in the list.
