### ISSUE TITLE
can't successfully build the package

### ISSUE THREAD

**Issue by asadwadood** [MISTLab/DOOR-SLAM#13]
hello,
thank you for your nice work.
i am trying to run the simulation package of DOOR SLAM, but it throws me error.
this link does not work #RUN wget -O argos3-package.deb https://drive.google.com/u/0/uc?id=19RZtiHKYhTA_SXzMLRSksH_zO5YXr_kR&export=download , so i manually downloaded the argos simulator and used .
even after this it throws error.
 the error is as follows.
![issue doorslam](https://github.com/MISTLab/DOOR-SLAM/assets/32166305/8c367116-11d6-4641-a2c8-131721361c6a)

can you please help me to solve this issue

**Comment by lajoiepy** [comment]
Hi! It seems that liblua-dev or its headers are missing. You can look at their doc for installation https://www.lua.org/download.html

In any case, I strongly suggest that you try our latest multi-robot SLAM system [Swarm-SLAM](https://github.com/MISTLab/Swarm-SLAM) instead, it is much better than DOOR-SLAM :smile:

**Comment by asadwadood** [comment]
Hello, I tried to Run with given Docker Image lajoiepy/doorslam-argos-simulation , but i can't see simulation. i think the error is related to argos simulator. Can you please help me in solving the issue. 
![argos1](https://github.com/MISTLab/DOOR-SLAM/assets/32166305/ae7c09b2-2039-486a-b504-aaae590adcab)
![argos2](https://github.com/MISTLab/DOOR-SLAM/assets/32166305/344674bb-6abe-405a-b92f-dd1290cab04c)

**Comment by lajoiepy** [comment]
Indeed, this looks like a Argos3 or Docker problem. Unfortunately, I cannot help with those issues since they are most likely specific to your system.
