### ISSUE TITLE
Why is RANSAC works well in centralized setting?

### ISSUE THREAD

**Issue by Janebek** [MISTLab/DOOR-SLAM#14]
Hi @lajoiepy! Great work of you guys!

I'm recently reading your paper "Towards Collaborative Simultaneous Localization and Mapping: a Survey of the Current Research Landscape",  which is really inspiring.

But I have one question, in the section 5.4 of the paper, you mentioned "While RANSAC works well in centralized settings, it is not adapted to distributed systems" , I got confused by this, I think there is no difference between centralized and distributed systems in terms of RANSAC procedure.

Could you please explain why is that?

**Comment by lajoiepy** [comment]
The statement might be to vague. What we had in mind is that the randomness in RANSAC prevents multiple agents to independently reach the same outcome. Moreover, it requires to perform the estimation/optimization at every sub-sampling iteration, which might not be realistic with costly distributed optimization.

I am closing this, as this is not a code issue, please email me instead for paper questions.
