### ISSUE TITLE
pcm src

### ISSUE THREAD

**Issue by gisbi-kim** [MISTLab/DOOR-SLAM#2]
I followed the code link and got the location of Buzz SLAM
https://github.com/lajoiepy/Buzz_SLAM/blob/658069e7c6248b40a4daf6b887132e36014460b8/src/slam/buzz_slam.h

and I've seen the distributed_pcm.h line, but I couldn't find where the src located. 
Where can I find the source of distributed_pcm.h and distributed_mapper.h ? 

Thank you.

**Comment by lajoiepy** [comment]
Hi! Thank you for your interest in DOOR-SLAM!
The files your are looking for are [here](https://github.com/lajoiepy/robust_distributed_mapper/blob/d609f59658956e1b7fe06c786ed7d07776ecb426/cpp/include/pairwise_consistency_maximization/distributed_pcm/distributed_pcm.h) and [here](https://github.com/lajoiepy/robust_distributed_mapper/blob/d609f59658956e1b7fe06c786ed7d07776ecb426/cpp/include/distributed_mapper/distributed_mapper.h).
If you don't find the files locally on your machine, you should try updating the submodules ( https://git-scm.com/book/en/v2/Git-Tools-Submodules )

**Comment by gisbi-kim** [comment]
Thank you! I newly learned the submodule and the command git clone --recurse-submodules https://github.com/MISTLab/DOOR-SLAM.git solved the problem.
