### ISSUE TITLE
where  is the  SLAM framework

### ISSUE THREAD

**Issue by holyly** [MISTLab/DOOR-SLAM#6]
Sorry,I didn't saw  the  SLAM framework in this code,forexample,where is the method of extract  feature point...And  is the code  complete? Is the project based on C++? I hope I will receive a reply as soon as possible..THANK U VERY VERY VERY MUCH!!!

**Comment by lajoiepy** [comment]
Hi!
To get the full code you have to pull the submodules:
```
git submodule init
git submodule update
```
then [here](https://github.com/MISTLab/DOOR-SLAM/tree/master/tx2-setup) you will see the SLAM front-end and back-end.
It is feature-based SLAM, we use [RTAB-MAP](https://github.com/introlab/rtabmap) for visual odometry and the loop closure features extraction (see [here](https://github.com/bramtoula/multi_robot_SLAM_separators/blob/2ce1fa45107e92bde5329d023565cf5eebe26004/ros_ws/src/multi_robot_separators/src/myRegistrationVis.cpp)).
I hope this answers your question, have a great day and thank you for your interest in DOOR-SLAM!

**Comment by holyly** [comment]
Now i get it，thank you!!!!!!!
